name: Documentation

on:
  push:
    branches:
      - main

env:
  CRYSTAL_VERSION: '1.0.0'
  CI: true

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}
      - run: shards install --ignore-crystal-version
      - run: crystal docs --project-name "TikToker" --canonical-base-url "https://absolab.xyz/tiktoker"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
